.editorconfig, .gitignore
This adds git ignore / configs for editors
=> add configs

src/bot.js, src/game.js
Log bot picks to allow future improvement in bot AI.
Bots have key `'bot': true` in the player picks list.
=> Add bot picks to cap

public/src/app.js, public/src/components/game.js, public/src/data.js, public/style.css, src/game.js, src/human.js, src/make/cards.js, src/pool.js
Add AKH, MPS_AKH, MM3
Add Leisurely Timer
Adjust timers
Adjust Foil Rarities
=> AKH, MPS_AKH, MM3, Leisurely Timer, Timer Adjust

public/src/app.js, public/src/cards.js, public/src/components/lobby.js, src/game.js, src/pool.js
Adds checkbox to:
- Sealed for 4-pack sealed
- Chaos for modern-only
=> Add 4 Pack Sealed and Modern-Only Chaos

public/src/app.js, public/src/cards.js, public/src/components/lobby.js, src/game.js, src/pool.js
Creates a new option for Chaos draft to pick 1 random rare/mythic, 3 random uncommons, and 10 random commons from all of MTG.
=> 'Total Chaos' option

public/src/components/lobby.js
Moved version to footer, added github link.  Has slight branding incorporated.
=> Move Version to Footer

public/src/app.js, public/src/cards.js, public/src/components/deck-settings.js, src/game.js, src/human.js
This is the answer of #34 
As you can see, there's still some to do (maybe control the name of the file, visibility - as it's seen also during the game and when we don't draft ). Any help would be appreciated :) !
Thanks,
=> Dev: add draft log

src/game.js
Hey,
I checked from the beta.draft.com and I controlled on my computer ... I had changed the name of the draftlog but didn't on the game.js.
So I changed the name and it works!
=> fix log passed to client App

README.md
re-organized and re-grouped phrases
=> restructure readme

src/pool.js
Combine same-function case statements
=> Switch statement cleanup

src/make/custom.js
Allows importing custom sets. `custom` needs to be enabled in `Makefile`.
=> Change custom to use MTGJSON formatting, allow multiple sets

src/make/score.js
Move score database to local file and update it
Still no tools to generate / update it live
=> Local score db

public/src/data.js, src/make/cards.js, src/pool.js
Wait to merge after mtgjson adds the set!
=> [DO NOT MERGE] Add Iconic Masters set

app.json, public/src/components/grid.js
Actually this is just to show the pack number.
I just have a question : the value of App.state.round may be -1 sometimes, but it means the game is finished. Should I take it in consideration ?
Thanks in advance,
Herve
=> close #19 - Show progress in draft - pack and pick number

public/style.css
Just added a padding of  1px to class css .card.
=> Fix #80: Separate cards 

.eslintrc.js, config/config.client.js.default, config/config.server.js.default, package.json, public/index.html, public/src/app.js, public/src/cards.js, public/src/game/Chat.jsx, public/src/game/Cols.jsx, public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx, public/src/game/PlayersPanel.jsx, public/src/game/StartPanel.jsx, public/src/init.js, public/src/lobby/CreatePanel.jsx, public/src/lobby/GameOptions.jsx, public/src/lobby/GameTypes.jsx, public/src/lobby/Header.jsx, public/src/lobby/JoinPanel.jsx, public/src/lobby/Lobby.jsx, public/src/lobby/NewsPanel.jsx, public/src/lobby/Set.jsx, public/src/lobby/Version.jsx, public/src/router.js, public/src/sets.js, public/src/utils.jsx, webpack.config.js
Hi, 
I've been trying to organize the code and I set up [ESLint](https://eslint.org/docs/user-guide/getting-started) on the app. 
It helps keeping always the same code pattern and also gives good advices while writing React components. The changes are mainly changes of single quote to double quotes and adding ";" at the end of every line. 
On the main components, it enforces the declaration of propTypes to keep track of the types expected by any component. The Chat component has been modified to not rely on "string ref" but follow  [the rules of ref attribute](https://zhenyong.github.io/react/docs/more-about-refs.html). 
I somehow added also some https instead of http call in the public/index.html file (just because it's safer and doesn't trigger any warning on a https server).
=> Add ESLint and refactored frontend

config/config.client.js.default
=> fix link display

package-lock.json, package.json, public/src/sets.js
This adds several sets that were missing
=> add additional sets

public/index.html
=> loading hint: remove alt text

public/src/sets.js, src/make/cards.js, src/pool.js
=> Dev: add M19 and basic cards; closes #122, closes #119 

package.json
Add a new dependency which became mandatory following the bump of webpack
=> Dev: add webpack-cli

src/pool.js
Filter the art of invocations when making cube
=> Dev: use invocation art only for the sets they appear. Closes #121

README.md
**Make sure #150 is merged before this!**
---
[![ci](https://travis-ci.com/dr4fters/dr4ft.svg?branch=master)](https://travis-ci.com/dr4fters/dr4ft)
[![dependencies](https://david-dm.org/dr4fters/dr4ft.svg)](https://david-dm.org/dr4fters/dr4ft)
[![devDependencies](https://david-dm.org/dr4fters/dr4ft/dev-status.svg)](https://david-dm.org/dr4fters/dr4ft?type=dev)
See https://github.com/dr4fters/dr4ft/tree/tooomm-patch-1#readme
=> README: add status badges

src/_.js
No cards with Æ exist anymore.
=> remove case for Æ

src/make/cards.js
=> Remove Extra Cards from DOM and M19

public/src/game/DeckSettings.jsx
=> Fix: able to change download filename. Closes #165

src/make/cards.js
=> Dev: add A25 set

public/src/cards.js
Closes #172 
Now the filename is took from the App filename. We just append -draftlog.txt at the end
=> Dev: adjust draftlog filename

public/src/game/Cols.jsx, public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx, public/src/game/PlayersPanel.jsx, public/src/lobby/CreatePanel.jsx, public/src/lobby/GameOptions.jsx, public/src/lobby/Set.jsx, public/src/utils.jsx
=> Fix: adjust keys of JSX arrays to stop the app from refreshing too much

.eslintrc.js, public/src/app.js, public/src/game/Game.jsx, public/src/router.js, src/api/sets.js, src/make/update_database.js, src/pool.js, src/util.js
=> Code cleanup following ESLint recommandations

src/game.js
Closes #103 
I chose to use "Infos" instead of writing in "Type". I feel that it's better to keep Type as is, as it shows what type has been chosen during game creation. Infos are more for the options passed IMO
=> Add room infos for chaos

public/src/game/DeckSettings.jsx
=> Show DownloadLog button only when the game is finished

public/src/game/Cols.jsx, public/style.css
Answsers #77 split and fuse request.
If a card has a layout of "split" (includes also the fuse cards), we rotate the card by 90 degrees.
=> Rotate card by 90 degree if card layout is fuse or split

public/src/init.js, public/src/router.js
Helps to speed up JS parsing and downloading as the JS files are split between our 2 main views
=> Split code between Game and Lobby views

public/src/game/Chat.jsx
=> Allow click in chat to focus input

public/src/app.js, public/src/game/Cols.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx, public/style.css
=> Allow user to set card's size (to decrease loading image time)

package-lock.json, package.json, public/src/game/Chat.jsx
=> Notify with toast a message when player has chatbox closed

src/human.js
=> Disable autopick for last pick

public/src/cards.js
=> Rename last cmc pile from 6 to 6/6+

public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/GameSettings.jsx, public/src/game/PlayersPanel.jsx, public/src/game/StartPanel.jsx, public/src/lobby/GameTypes.jsx, public/src/lobby/Header.jsx, public/src/lobby/Set.jsx, public/src/utils.jsx
=> Capitalize stuff

public/src/game/Game.jsx, public/src/game/PlayersPanel.jsx
=> Fix name warning

package-lock.json, package.json, public/src/app.js, public/src/cards.js, public/src/game/Chat.jsx, public/src/game/Cols.jsx, public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx, public/src/game/PlayersPanel.jsx, public/src/game/StartPanel.jsx, public/src/lobby/CreatePanel.jsx, public/src/lobby/GameOptions.jsx, public/src/lobby/GameTypes.jsx, public/src/lobby/Header.jsx, public/src/lobby/Lobby.jsx, public/src/lobby/Set.jsx, public/src/router.js, src/game.js, src/make/allsets.js, webpack.common.js
This fixes the filename issue not being loaded correctly, a possible issue with the AllSets.json download and cleanup some packages / configs from webpack
=> Cleanup and fix

package-lock.json, package.json, public/src/app.js, public/src/router.js
New fix for filename (that deletes luxon because it's just too big a library for just parsing date ...)
=> Fix filename

public/src/game/Game.jsx
Wanted to clarify the location.
Opinions please.
=> rephrase nickname msg

public/src/game/Chat.jsx, src/game.js, src/human.js
=> fix timer and event emitter bug

package-lock.json, public/src/game/StartPanel.jsx
=> capitalize type of game

src/game.js
=> set 4 packs sealed shows up correctly

public/src/app.js, public/src/game/PlayersPanel.jsx, public/src/game/StartPanel.jsx, public/style.css
Closes #369
Also found a bug with StartPanel toTitleCase. I set a default string for the phrase variable because the value could be not initiated (when you refresh the page for example)
=> Remove unused info for non-draft modes

package-lock.json, public/src/app.js, public/src/cards.js, public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/PlayersPanel.jsx, public/src/game/StartPanel.jsx, public/src/lobby/GameOptions.jsx, public/src/lobby/GameTypes.jsx, public/src/lobby/Set.jsx, public/src/utils.jsx, public/style.css, src/api/games.js, src/game.js, src/util.js, test/game.spec.js
Closes #64 
Closes #149 
[UPDATE: add chaos sealed and draft pack number]
=> Refactor gametypes

package-lock.json, public/src/app.js, public/src/game/Game.jsx, public/src/game/GameSettings.jsx, public/src/game/PlayersPanel.jsx
Add option to hide selected picks during draft to simulate a more realistic draft
Fix #45
=> Hide selected picks option

.travis.yml
There is a problem with node v12 (https://github.com/dr4fters/dr4ft/issues/461)
=> default to node 11 for now

.travis.yml
Reverts dr4fters/dr4ft#468
See https://github.com/dr4fters/dr4ft/issues/461#issuecomment-492161511
=> Revert "default to node 11 for now"

src/make/doSet.js
=> use isAlternative to skip japanese pws

src/game.js, test/game.spec.js
=> Fix game max rounds to accept more than 3

src/data.js
=> do not let spoiler as possible default value for playable set

public/style.css
=> fix: set image helper above chat

public/src/game/GameSettings.jsx
I wasn't 100% happy with the wording.
Is it clearer now? Does this make sense?
=> reword hide picks

src/data.js, src/make/doSet.js, src/make/update_database.js, src/pool.js, test/pool.spec.js
closes #482 
I added TimeSpiralTimeshifted (TSB) to have all the timeshifted cards in a separate set. Then when creating the pool, I add a random Timeshifted card.
=> add timespiral

src/make/doSet.js
=> fix aftermath cards names

README.md
remove dr4ft.com
~~add trsbox~~
=> README: update known sites

public/src/app.js, public/src/lobby/Lobby.jsx, public/src/lobby/Version.jsx, src/make/allsets.js, src/mtgjson.js, src/pool.js, src/sock.js, webpack.common.js
closes #518 
PS: also fix a test of past PR about Time Spiral set
=> Have proper version + date in footer

public/src/lobby/CubeList.jsx
Just looks better than a single-line textarea.
=> Better look for cube list entry.

public/src/router.js, src/mtgjson.js
=> clean version from build metadata to appear nicely in changelog

public/src/cards.js, public/src/game/DeckSettings.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx
closes #686
closes #687 
As we don't want to break compatibility with previous version, I had to add new variables to hold the GUI display informations.
=> Fix zone names display and wrong terminology for cards quality

src/game.js, test/pool.spec.js
closes #588 
The chaos draft was not working because the rounds value of the game (the limit of rounds to play) was not set correctly.
=> fix chaos draft

public/src/router.js
closes #688 
Save state of chat (do not override the value to true in our case)
=> save state of chat

public/src/cards.js, public/src/game/GameSettings.jsx
=> move only future picks to sideboard

public/src/game/Cols.jsx
=> fix zone name of zone

public/src/game/Game.jsx
closes #357 
I put back the GameSettings at the same place. It seems to work on my PC.
=> keep GameSettings at the same place

public/src/utils.jsx
=> Show more than one line/card for cube list

public/src/lobby/Version.jsx
=> Adjust link to mtgjson changelog

public/src/cards.js, public/src/game/Cols.jsx, public/src/game/GameSettings.jsx, public/src/game/Grid.jsx, public/style.css, src/make/doSet.js
closes #614 
closes #743 
It's a first attempt. Tell me what you think about it
=> implement card text

public/src/game/Grid.jsx
closes #767 
This is a regression of the Text-Only PR which modified the <CardImage /> prop.
=> fix: flipped card issue

.travis.yml
To align better with the other names.
`TEST` --> `Run tests`
=> rename travis job

backend/game.js, backend/game.spec.js
This should fix a bug on how we display roomInfo. Right now there's an error in the code - we don't show public but private games ... 
I added some tests to be sure that it will work
=> fix: show roomInfo for public games

backend/data.js
closes #899
The "box" sets cause some cards to be shown in cube in a non-english language.
I just removed these cards to be cubable.
=> fix: do not include box cards as cubable card

backend/api/sets.js, backend/data.js, backend/import/doSet.js, backend/import/toBoosterCard.js, backend/import/xml/parser.js, backend/import/xml/parser.spec.js
closes  #904
closes #892 
I also fixed some bugs of the integration of custom sets.
=> fix upload cockatrice v3 support

backend/game.js, backend/rooms.js
Checking the logs on beta-draft, I saw that we have an error when a game is killed by the timeout process. 
This PR is a fix for this problem
=> fix error when a game is killed by timeout

scripts/update_database.js
=> integrate all sets from MTGJson

backend/api/sets.js
add a missing check on the custom directory
=> fix create the custom directory if not exists

backend/boosterGenerator.js
closes #913
The problems was on the algorithm to find cards depending on the color balance. There was a flaw and this PR solves it.
=> fix color balance of cards

frontend/src/game/Cols.jsx, frontend/src/game/Grid.jsx
closes #865
Hi @user6174 could you try upload and check if you can see your cards now?
=> fix display custom images

frontend/src/app.js, frontend/src/cards.js, frontend/src/game/Cols.jsx, frontend/src/game/GameSettings.jsx, frontend/src/game/Grid.jsx, frontend/style.css
closes #900
Allow to select the language of the cards displayed. 
I took the list from scryfall
=> support language image settings

frontend/src/cards.js, frontend/src/game/GameSettings.jsx
=> decouple beep and desktop notification

frontend/src/game/Cols.jsx
=> change formatting

backend/game.js, frontend/src/cards.js
=> Update Pack Size

frontend/src/game/Game.jsx, frontend/src/game/Grid.jsx, frontend/style.css
Small change to indicate when the user is waiting for another user to pass a pack.
Just used the text that MTGO does.
=> feat: indicate that the user is waiting on another pack

package-lock.json, package.json, webpack.common.js
Purges the contents of the `built` directory whenever a new package is made. This will help to reduce the clutter in that directory, especially during dev watch.
=> misc: add CleanWebpackPlugin to clear built directory on build

frontend/src/game/PlayersPanel.jsx
Ease the change of the player name (as it's weird right now to change it from the Player Panel with the lags)
=> Smooth change name fro Player panel

frontend/src/game/GameSettings.jsx
Include language names in their own form.
Translations taken from Cockatrice translations at Transifex.
=> Update language setting options

backend/game.js, backend/logger.js, backend/router.js
add some more log to the game (when a new player joins, is being kicked or when a game ends)
=> log some game events

backend/game.js, frontend/src/app.js, frontend/src/game/PlayersPanel.jsx
fixes the game seat number shown in the playerpanel.
First introduced in #935 but it was using the wrong variable, so I had to use a dedicated one.
=> fix gameseats display

app.js, backend/data-watch.js, backend/data.js, backend/game.spec.js, backend/import/keyCards.js
closes #951 
@ZeldaZach I changed also how cubable cards are saved (instead of saving the whole card, I just save the UUID and then I search in the cards.json DB) so you will need to reload the db after applying this change.
=> Watch data files

backend/api/sets.js
closes #925 
Save only what we need from the custom sets. especially don't allow saving uuid that could disrupt the main system.
=> sanitize the incoming json

app.js, package.json, scripts/download_booster_rules.js
Add a daily check on booster rules (via the github API) to fetch any new version of booster rules.
=> add check on booster rules

frontend/src/game/GameSettings.jsx
=> hide image language on text-only mode

backend/import/toBoosterCard.js, backend/import/toBoosterCard.spec.js, frontend/src/app.js, frontend/src/cards.js, frontend/src/game/Cols.jsx, frontend/src/game/Grid.jsx
closes #767 
I broke the display of flipped and double faced cards by introducing the image lang option. I also expanded the language to the card preview that was also not showing the right card language.
=> fix double faced cards display

frontend/src/game/Grid.jsx
I introduced a regression on working on last PR, now the cards don't refresh when you change the card lang. This PR fixes it.
=> fix refreshing cards lang

Dockerfile, README.md, backend/api/sets.js, backend/data.js, backend/data.spec.js, backend/game.js, backend/import/toBoosterCard.spec.js, frontend/src/lobby/GameOptions.jsx, scripts/download_allsets.js, scripts/download_booster_rules.js, scripts/update_database.js
Hello! My friends and I really enjoy dr4ft.info and I thought I'd see if I could start contributing somehow. 
This PR is an attempt to remove the requirement to run `npm install` with superuser permissions and the `--unsafe-perm` flag.
The `postinstall` steps defined in `package.json` run a few scripts which use [`fs.mkdirSync()`](https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options) to create a `./data/` directory and subdirectories for card and set metadata.
Without the `sudo` and `--unsafe-perm` flag I was getting an `EACCES` error. Looking at the mkdir [man pages](http://man7.org/linux/man-pages/man2/mkdir.2.html#ERRORS), this error happens when [path resolution](http://man7.org/linux/man-pages/man7/path_resolution.7.html) fails.
Use absolute paths instead of relative paths for …
=> Remove need for sudo and --unsafe-perm

frontend/src/cards.js, frontend/src/game/Game.jsx
closes #799 
It's a starting point, let me know what you think about it @ZeldaZach @tooomm
=> reset window position on new pack

frontend/src/game/PlayersPanel.jsx, frontend/src/game/StartPanel.jsx, frontend/src/lobby/CreatePanel.jsx, frontend/src/lobby/CubeList.jsx
- `Create Room` button
- Explanation on how to enter a cube list
- cube `ID`
- `Start Game` button
- `Kick` button
=> Capitalize leftovers in UI

.eslintrc.js, backend/data.js, backend/game.js, backend/human.js, backend/import/toBoosterCard.js, backend/import/xml/parser.js, backend/player.js
closes #1019
Added these rules:
- [enforce camelCase](https://eslint.org/docs/rules/camelcase)
- [no multi-space](https://eslint.org/docs/rules/no-multi-spaces)
- [no trailing spaces](https://eslint.org/docs/rules/no-trailing-spaces)
=> configure linter to catch extra spaces + camelCase

README.md, backend/boosterGenerator.js, backend/data.js, backend/sock.js, frontend/src/lobby/Lobby.jsx, frontend/src/lobby/Version.jsx, scripts/download_allsets.js, scripts/download_booster_rules.js
closes #1024 
added a fix on download of allsets too
=> Booster rules version

frontend/src/lobby/Version.jsx
=> Tweak footer wording

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
After seeing them live I made some more little changes.
=> Further template tweaks

frontend/src/events.js, package-lock.json, package.json
- closes #1022 
XSS attack is possible via the "Toat" feature (message sent via toast when the Chat window is closed.
Used the library [DOMPurify](https://github.com/cure53/DOMPurify) to sanitize the messages
=> sanitize messages

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/issue_template.md, .github/PULL_REQUEST_TEMPLATE.md
- Add a useful basic template once users opt for the "non-bug, non-feature" option
- More wording updates
I promise, I'm done now 😆🤞
=> More template changes

frontend/src/lobby/GameOptions.jsx
Use `[explanation]: [value]` as we do in all interface.
I also changed the display a bit and used a more detailed description for the options.
=> cube options ui improvements

backend/util.js
User facing error messages are now displayed with a capital letters in the interface.
=> Capitalize user facing error messages

frontend/src/lobby/CubeList.jsx
- Fixes #1130
We were using `save` incorrectly. So the list variable never got updated.
Fixup the usage of `save`
=> Fixup cube cobra integration

README.md
Use discord badge to point to our main chat.
Gitter is not really used for the project anymore.
=> exchange gitter for discord

backend/util.js, frontend/src/lobby/CreatePanel.jsx, frontend/src/lobby/CubeList.jsx
- Uniform usage of quotes and fullstops
- Capitalization of placeholder for room title and cube list
- Use worldwide standard number grouping
- More helpful error message on cube list length
=> Little fixes

frontend/src/game/GameSettings.jsx, frontend/src/game/GameSettings.scss, frontend/style.css, package-lock.json, package.json, webpack.common.js
- Fixes https://github.com/dr4fters/dr4ft/issues/1155
Settings radios were not visible
- change settings to be highlighted buttons
- add scss support
- made making this change easier
- should make future design changes better scoped, easier to maintain
=> fix settings radio buttons, add scss support

backend/game.js, frontend/src/app.js, frontend/src/events.js, frontend/src/game/Grid.jsx, frontend/src/gamestate.js, package-lock.json
- Fixes #1169
the bug: on the backend the players (bot or human) had been assigned the correct PickPerPack value, but the frontend never receive that number for the human players that are not the host.
this commit fix that bug
-> Add PicksPerPack variable to the event GameInfo / UpdateGameInfo.
-> Remove PicksPerPack from the method initGameState. 
-> Add picksPerPack as the last  parameter in updateAutopick() and isAutoremovableAutopick() in the frontend.
=> Fix Bug: Only host known PicksPerPack Value

backend/import/toBoosterCard.js
use less data from identifiers to have a lighter client and server
=> remove unused data from identifiers

frontend/src/events.js, frontend/src/game/Game.jsx, frontend/src/game/Grid.jsx, frontend/src/game/Grid.scss, frontend/src/game/card/CardGlimpse.jsx
adds a confirm button which lights up blue when you can confirm a selection of picks
=> add a confirm btn as an alternative way to lock in selections

frontend/src/game/card/CardBase.scss
fixed the shrunk images for low-res
=> fix small image size

README.md
Old Travis CI badge
Use GH Actions one and link to filtered list
=> Use GitHub Actions badge

frontend/src/game/card/CardBase.jsx, frontend/src/game/card/CardBase.scss, frontend/src/game/card/CardDefault.jsx, frontend/src/game/card/CardDefault.scss, frontend/src/game/card/CardGlimpse.jsx, frontend/src/game/card/CardGlimpse.scss, frontend/src/game/card/SelectionState.jsx, frontend/src/game/card/SelectionState.scss
- Fixes https://github.com/dr4fters/dr4ft/issues/1394
Double-sided cards were not flipping correctly in the pack area. I've moved some things around and was able to delete some code! hooray, it also now works
=> ensure double-sided cards flip in pack area

frontend/src/lobby/CubeList.jsx
Download card versions from CubeCobra
Rather than using the default card versions for cubes downloaded from CubeCobra, this fetches the versions that the user has specified for their cube. In combination with #1302, this means that dr4ft.info will use the same card images as CubeCobra.
=> Cobra versions

backend/data.js
- Fixes #1411
Preventing funny sets (unhinged...) from being picked as random set
=> prevent funny sets from being chosen as random set

frontend/src/config.js
Cleanup the frontpage.
As mentioned in https://github.com/dr4fters/dr4ft/pull/1433, the repo README has this information already. Also not part of the new design draft.
=> Move repo history

README.md
=> README: update feature list

frontend/src/export/mtgo.js, frontend/src/export/mtgo.spec.js
Thanks to feedback and testing from @LotusWalker , we've determined an edge case bug for the MTGO export.
The details of the gotchas and the current improved solution are recorded in the code
=> patch MTGO export

frontend/src/lobby/FileUpload.jsx
@ZeldaZach this disables JSON uploads, but allows XML which I think were working ok...
=> TEMP: disable JSON upload of custom sets

backend/import/toBoosterCard.js, frontend/src/export/cockatrice.js, frontend/src/export/cockatrice.spec.js, frontend/src/export/index.js, frontend/src/export/mtga.js, frontend/src/export/mtga.spec.js, frontend/src/export/mtgo.js, frontend/src/export/mtgo.spec.js, frontend/src/export/test-cards.js, frontend/src/game/DeckSettings.jsx, frontend/src/game/DeckSettings.scss, frontend/src/game/GameSettings.scss
fixes https://github.com/dr4fters/dr4ft/issues/1454:
- changed mtgo export to just use `.txt` files
fixes https://github.com/dr4fters/dr4ft/issues/1242:
- added tests around "meld" layout cards
=> Export again!

frontend/src/game/Cols.jsx, frontend/src/game/Cols.scss, frontend/src/game/card/CardBase.jsx
This PR is here to make it easy to see the changes I've made to the branch `card-changes` by @Noojuno
=> fix card flip logic, reduce listeners

app.js
Fix linting for [`82842b0` (#1464)](https://github.com/dr4fters/dr4ft/pull/1464/commits/82842b0f1a93659367d81b5df9934317a8dd1200)
=> fix linting, prettify comments

frontend/src/game/card/CardBase.jsx, frontend/src/game/card/CardBase.scss, frontend/src/game/card/SelectionState.scss
=> Card text improvement

frontend/style.css
- Fixes #1467 
Changed the container to have `min-height: 100vh`
=> fix bottom page spacing

README.md, doc/api.md, doc/design.md
Added a toc, more clearance, highlighting etc.
The content of the design one is probably outdated. Feel free to look into that.
=> Docs: Improve readability

frontend/src/game/GameSettings.jsx, frontend/src/game/card/CardBase.jsx
There was a bug where changing the card quality didn't immediately update the quality of images loaded (you had to go via text mode then to a different quality).
This fixes that!
=> fix: card-quality settings

backend/game.js, backend/util.js, backend/util.spec.js
Modifies random bot placement to placement using a distribution algorithm to achieve more even placement in seats.
Distribution function added to util.js to be independently testable from the Game class.  Unit tests added.
- Fixes #1692
=> distribute bots more equally between players

backend/game.js, frontend/src/config.js
Links took users away from dr4ft page.
Open links in new tab instead.
It's suggested to secure them with `rel="noreferrer"` as well.
=> Open links in secure new tabs
