src/pool.js
According to [this article](http://www.mtgsalvation.com/forums/magic-fundamentals/magic-general/768235-what-are-current-pack-odds-including-foils) foil basics occur at a rate of approx 2/15. We'll discard those 2/15 and end up with 1/6.92 or approx 1/7 odds of getting a foil other than a basic land.
Closes #8
=> Account for Basics when inserting foils

public/src/data.js
Change Magic origins from "other" sets to "core"
Reference : https://mtg.gamepedia.com/Magic_Origins
Quote : Magic Origins is the 17th Magic core set
=> Change Magic Origins from "other" sets to "core"

src/make/cards.js
Set 'CPK' is no longer in mtgjson. Was causing make error. Now sets to delete are an array and are verified before removal.
Time Spiral Timeshifted (TSB) are now inserted 1/pack
=> Verify sets to remove. TSB to special rarity.

public/src/components/cols.js, public/src/components/grid.js, public/style.css, src/make/cards.js
This pull adds 
1. show flipped face during mouseOver on doublefaced cards
2. show the two faces of double-faced cards on main and and side zones, thanks to imageHelper popup.
=> Close #52 - Managing Doublefaced cards

public/style.css
fixes #59
Screenshot from HerveH44's Heroku instance at https://beta-dr4ft.herokuapp.com/ with his refactor branch:
---
Taken from https://github.com/HerveH44/dr4ft/commit/96d0122c1f67d4828cce602e9bf9bb160d350f6d
(as part of this branch: https://github.com/HerveH44/dr4ft/tree/refactor_frontend)
originally by @HerveH44
=> Add padding - visually separate card piles

public/index.html, scripts/postinstall.js, webpack.config.js
Hi, 
I witnessed that the bundles (react and app) are atrouciously large (1.8MB and 2.2MB). After checking, I chose to go with a simpler route: we exclude react bundling but take it from the node_modules sources, just like we actually do with other libs (utils.js, ee.js, engine.io ...). It reduced the total from 4 MB to ... 500kB !! The app bundle is now 390k and react and react-dom is around 110k total. I guess we could put up some development / production differences (like uglify, or use of react development bundles which are bigger but shouts in the console any possible code improvement). But right now, I feel pretty happy with this setup.
Summary:
- Before **4MB**
- After **500KB**
As a nice side-effect, you can see the PR deployed on heroku and see the difference …
=> Optimize webpack bundling

README.md
Link to `BabelJS` wasn't defined.
If this is the correct repository, please merge @HerveH44
=> README: fix linking

.travis.yml, package.json
First version of working Travis CI:
- Install test on Node.js, which should had spotted the need for https://github.com/dr4fters/dr4ft/pull/145.
- Added ESLint check
- Added Node.js LTS
- Added check for Dockerfile
New GitHub Checks API in action: https://github.com/dr4fters/dr4ft/pull/150/checks
Note, that there is currently still a bug with the new Travis App for GitHub and builds are reported and shown twice, tracked in https://github.com/travis-ci/travis-ci/issues/9618:
>Yes, right now we're reporting the status two times per build triggered, one for the previous commit statuses and another one via GitHub Checks.
>
>We are aware of this issue, and we are working to clean it up in the coming weeks.
>
>Thank you for your understanding and patience.
---
This PR should be merged before …
=> CI: enable travis

.eslintrc.js, config/config.client.js.default, config/config.server.js.default, package-lock.json, scripts/app.js, scripts/postinstall.js, scripts/run.js, src/_.js, src/bot.js, src/data.js, src/game.js, src/hash.js, src/human.js, src/make/allsets.js, src/make/cards.js, src/make/custom.js, src/make/index.js, src/make/score.js, src/pool.js, src/room.js, src/router.js, src/sock.js, src/util.js, webpack.config.js
This supersedes https://github.com/dr4fters/dr4ft/pull/152.
It's the same, just with cleaner commits:
>I only run `eslint --fix`, `npm audit fix` and updated the *.eslintrc.js* file to removed a hint about deprecated options.
=> run eslint + npm audit

package-lock.json, package.json
Realized the mismatch and non-uniform linking here: https://david-dm.org/dr4fters/dr4ft
Now only links to our own forks, so we are no longer dependent on repos we don't control.
=> Repo cleanup: Unified dependency linking to our own forks

public/src/sets.js, src/make/cards.js, src/pool.js
Support dominaria constraint for Legendary creatures following rule : 
Each booster is arranged so one of the uncommon or rare/mythic rare slots is filled with a legendary creature.
http://markrosewater.tumblr.com/post/172581930278/do-the-legendaries-that-appear-in-the-legendary
=> Dev: add Dominaria support.  Closes #118

.gitignore, package.json, public/index.html.tpl, webpack.config.js
As #185 showed, people have problems when we update the app, because their browser caches the javascript and can creates problem. 
I updated the webpack configuration to create everytime a new app bundle with an hash based on the app file content. Doing so, the browser will think it has to download a new file every time we update our websites and it will no longer keep old cache.
=> Bypass browser cache

.travis.yml
The minimal image also has docker included:
https://docs.travis-ci.com/user/languages/minimal-and-generic/
=> travis: use minimal over generic for docker build

public/src/app.js, public/src/cards.js
=> Sort packs by rarity by default

public/src/game/Cols.jsx
=> Refresh card image after click 

README.md, package-lock.json, package.json, public/src/app.js, public/src/cards.js, public/src/game/Cols.jsx, public/src/game/DeckSettings.jsx, public/src/game/Game.jsx, public/src/game/Grid.jsx, public/src/game/StartPanel.jsx, public/src/lobby/GameOptions.jsx, public/src/lobby/GameTypes.jsx, public/src/lobby/Header.jsx, public/src/lobby/Lobby.jsx, public/style.css, src/_.js, src/api/games.js, src/data.js, src/game.js, src/human.js, src/pool.js, src/sock.js, src/util.js, test/game.spec.js, test/pool.spec.js
This one is a big baby. I rewrote the part where the server creates the pool (packs of cards) to have a specific entry for every type of game we handle.
I haven't touched at the packs creation in se (with all the specific rules depending of the set), just clarified how we create a cube pool, normal pool or chaos pool.
Closes #68
I added the mode chaos sealed. It takes the same parameters as chaos draft.
Closes #25
I then pushed a little bit to introduce "cubePoolSize" a new variable to adjust the number of cards a cube  player can have in his sealed.
Closes #27
In the end I also added the cube hash requested by @dev-id  to the draft cap. I used md5, is it 
Closes #350
I also cleaned up a bit code when I saw there was something old (readyToStart feature parts for example)
=> Refactor pool generation

README.md
It looks like .com is down currently.
Any news if @dev-id is doing an update etc. or if the page is gone?
---
@ZeldaZach could you update the dr4ft page link in the repo to be https please?
=> update known pages

src/pool.js
Preemptively adding this PR in preparation for MTGJson pushing finalized WAR data.
Functionality modeled after DOM Legendary Creatures functionality
Source: https://magic.wizards.com/en/articles/archive/feature/closer-look-stained-glass-planeswalkers-2019-03-08
=> Add a planeswalker to every WAR booster

src/pool.js
Fix bug allowing multiple planeswalkers in WAR boosters.
Fixes #445
=> Force only one planeswalker in WAR boosters (not including foils)

package-lock.json, package.json, src/make/allsets.js
unzip has been abandoned for about 5 years. this pr switches to using uzipper, an updated fork with a drop-in compatible api.
this fixes an issue encountered by @ZeldaZach when deploying to dr4fts.info which prevented him from successfully unpacking at least one set archive.
=> Switch from unzip to unzipper

src/pool.js
Tried to read the supertype, for more concise code, but it did not work.
=> Issue #495 - Add one basic snow land per pack.

src/data.js, test/data.spec.js, test/pool.spec.js
closes #388 
I loosened the control on playable sets. After checking how starters can be divided as playable / non playable, I found that all playable starter sets have baseSetSize different of 0.
=> Add playable starter sets

public/src/lobby/Version.jsx
Since MTGJSON uses semver with leading `v` it makes more sense to have this styling.
old: `Using MTGJSON card data version: v4.5.0-rebuild.5 (2019-09-14)`
new: `Using MTGJSON card data v4.5.0-rebuild.5 (2019-09-14)`
Screenshot:
=> changes to mtgjson version display

package-lock.json, package.json, src/make/allsets.js
Version checking is broken because we don't control properly the version style. 
This PR implements semver control using the library [node-semver](https://github.com/npm/node-semver/).
Closes #679
=> Add semver control for MTGJson version

src/make/doSet.js
I found out that ELD adventures cards' names could be simply parsed as we do for split and aftermath cards.
@tooomm could you test on Cockatrice as I don't have it.
closes #624
=> fix parse name of adventure cards

public/src/game/GameSettings.jsx
closes #712 
Added a control on rendering of the following options:
- "Hide your picks"
- "Beep on new packs"
=> Hide unnecessary options in sealed mode from UI

public/src/game/GameSettings.jsx
We always use descriptive labels for the options in settings, not only tag words.
Fix that for "Column view".
=> uniform wording in settings

public/src/game/GameSettings.jsx
Expand on https://github.com/dr4fters/dr4ft/pull/717
I think it could still be useful to have this option displayed before a sealed game starts so that somebody could decide to "open his packs" in the sideboard to start building from there - move playable ones or his final cards to main deck, while throwing rubbish to the junk zone. Doing this manually takes a while.
But mostly this option is not needed.
But then the wording **picks** would not be precise still. (--> `Add cards/packs to sideboard`)
Played around a bit to have it check for sealed mode and if a game started without luck. :P
=> More situational hide

public/src/game/PlayersPanel.jsx
closes #725 
I chose not to hide arrows for the host, because it's more code to write and it doesn't feel right to me to move the other players when you want to move yourself.
=> hide move arrows when single player

public/src/cards.js, src/pool.js, test/pool.spec.js
closes #753 
It appears that the capitalization of Colors and Rarity introduced a regression to how RNA and GRN packs are generated. 
This PR solves the problem by checking the correct rarity (Common instead of common) and also adds checks on others colors' types. 
Though everything would need a refactor to use the types from an enum or something. 
@ZeldaZach Does MTGJson holds JSON schema with maybe enums for colors, rarity etc?
=> fix RNA pack

public/src/game/GameSettings.jsx
Partially addresses #744
The first is somehow a general switch.
The first turns beep notifications on.
The second is only selectable once the first is enabled.
The second disables the beep from the first.
The second enables desktop notifications via the browser (likely to trigger an os sound on notification event).
It's quite difficult to make clear that the options are dependent on each other, and how ticking the first is needed for the second even though the second disables something the first was providing (beep sound) while superseding that with a web notification and a different system sound most probably.
<br>
**This is a first, simple approach to improve the wording for now.**
---
A better solution would be to also stress the dependence from the first, and/or group the two …
=> Improve wording for notification settings

public/src/lobby/GameOptions.jsx
closes #757
This applies to both sealed and draft as they share the same options. I don't think that's a problem.
=> set lower pack number to 1

public/src/app.js
#closes 760
Notify value wasn't saved because it was not present in the default state of the app
=> add notify default value

test/pool.spec.js
closes #770
Added a test to check if 1000 EMN boosters have double cards that are not expected (not "special", meaning not double-faced card or foil)
=> check emn double cards in booster

scripts/update_database.js
fixes #860 
@ZeldaZach if you accept to allow box set types to be part of our DB (but still not draftable / sealedable) you can accept this PR. 
It's a quick fix, just added the "box" set type (as GN2 has this type in MTGJson).
=> add box as an acceptable set type

backend/data.js
fixes #883 
Actually it's a regression, we used to filter out the masterpieces before (see #121) from the v1.0
=> fix: cube cards must not be from masterpiece set

backend/data.js, backend/import/keyCards.js
This PR is intended to sort the cubable cards in order to show playable versions of the card whenever possible and if no playable version of the card is found just show the first one found.
=> sort cubable cards by priority

backend/data.js, backend/import/keyCards.js
I found an interesting error in the logs, some special card (Hanweir Garrison) could not be cubable.
After checking, I found out that the cubable card grouping was skipping cards with a special number (like 123a) because it wasn't a real number. So I added a parseInt to cast the number to a pure int.
=> Fix cubable cards

backend/data.js, backend/game.spec.js, backend/import/doSet.js, backend/import/keyCards.js, backend/import/keyCards.spec.js
closes #891 
I deleted the contol on baseSetSize to allow all sets that don't have this value in mtgjson to be playable (and this means a ton). Just check on the PR deployment to see by yourself.
Mystery boosters are available and playble from what I tested.
=> allow mosts sets to be playable

frontend/src/game/PlayersPanel.jsx, frontend/src/game/StartPanel.jsx, frontend/style.css
Combined these because they're small and didn't want to flood PRs.
* Displayed player count in Players panel.
* Use css to align input checkboxes and radio buttons rather than whitespace.
* Try to expand on what "Bots" checkbox implies.
* Modify visible columns in Players panel based on draft state/type.
The column visibility change should be revisited. It doesn't account for the Kick/Move player admin options, which already display a visual issue without other players. Also not entirely sure that Kick works once a draft has started, that's either a defect or it means that the Kick button should be hidden after the game has started.
=> misc: styling tweaks

frontend/src/game/StartPanel.jsx
Improve grouping of options.
Might help with https://github.com/dr4fters/dr4ft/issues/897#issuecomment-603027907, too.
A new "paragraph" above the two timer options would be even better.
=> Swap game options

.babelrc, backend/boosterGenerator.js, backend/human.js, backend/pool.js, backend/pool.spec.js, frontend/src/app.js, frontend/src/cards.js, frontend/src/game/Cols.jsx, frontend/src/game/DeckSettings.jsx, frontend/src/game/Grid.jsx, frontend/src/gamestate.js, frontend/src/router.js, package-lock.json, package.json
closes #969 
This is a big change of how we handle cards in the frontend. Until now we were using a global list of cards that we were accessing by name which resulted in the bug depicted in #969 when two different cards with the same name were indistinguishable (when you clicked on one, it would click on both, or they would be both foil when only one should be, or the contrary, none of them would be foil when one should be). This was an issue on how we saved the cards. 
I changed that by introducing a new class "GameState" that handles the state of the different zones' cards. It helped also implement a nice feature which is that when you click refresh (f5) the cards disposition (your main / side cards, number of lands you inserted). I really feel that would be helpful. 
It still needs …
=> Fix multi card same pack

frontend/src/app.js
`-` is already used for the separation of year, month and day (e.g. `2020-04-23`)
Will change the suggested filename
from `IKO-draft-2020-04-23-24523`
to `IKO-draft_2020-04-23_24523` for easier reading.
---
As seen above, the time value is still cryptic and needs proper conversation to local user time.
=> Better separation of date and time in filename

frontend/src/app.js
The predefined filenames for deck downloads used to be `chaos-draft_2020-04-23_48265`.
Now it holds the proper local time for every user `chaos-draft_2020-04-23_15-26`.
Format is <kbd>GAMETYPE</kbd> _ <kbd>YYYY-MM-DD</kbd> _ <kbd>HH-MM</kbd>
=> use local user time

backend/boosterGenerator.js, backend/data.spec.js, backend/import/toBoosterCard.js, backend/import/toBoosterCard.spec.js, backend/import/xml/parser.js, backend/import/xml/parser.spec.js, backend/mtgjson.js, scripts/download_allsets.js
closes #960
@Kumarbis could you test on this PR deploy if you can import your custom set ? 
This is a fix to the import of the special split cards. 
I also fixed the split card color bug (we didn't take in consideration the other half color) and extended the "getDatadir" usage from #979
=> Fix import cockatrice v4

scripts/download_allsets.js
As [MTGJson](https:/mtgjson.com/) versioning also uses metadata, we need to check them in order to know if we need to update our DB. 
This PR changes the version check from strict (without metadata) to metadata check (with the function compareBuild)
=> Add check to version metadata when comparing mtgjson version

scripts/download_allsets.js
As suggested in #1006 we should fail instead of continuing when an error occurs during npm install (or run the download_allsets script)
=> do not catch errors during integration of AllSets

frontend/src/events.js
This adds a reset pack for the autopick event on frontend. 
It's related with the #1017 issue but do not solve all of it.
=> reset pack after autopick

frontend/src/app.js
Fix issue https://github.com/dr4fters/dr4ft/issues/1034 introduced by https://github.com/dr4fters/dr4ft/pull/990 where:
1. The set dropdowns momentarily flicker back to the default set (currently Ikoria) when creating a game room if a set other than the default was chosen.
2. When returning to the Lobby page, rather than remembering set selections all the sets were reset to the default.
=> ISSUE-1034: Fix sets flickering and not remembered

backend/data.js
Truncated GitHub hashes for commits are 7 digits, not 8.
=> fix hash lenght

app.js, package.json, scripts/download_allsets.js, scripts/download_booster_rules.js, scripts/run.js
Fixes the problem of playing when an update of the DB is made. As all DB actions are still synchronized and an update may take couple 10s of seconds, when an update occurs it provokes a big latency for the players. When a DB updates, the server will not respond to players until the update completed, this leads to "game crashed feeling" from the drafters as during the time taken by the update to complete, they lost time and some picks may have been "autopicked". 
Move all the scheduled updates to a new node process. Doing so the update will not affect the players. The update will still have an impact on the current process given that we use a "data watch"
=> update DB in another process

backend/boosterGenerator.js
No issue yet :D
This PR tends to solve the colorless card absurd probability representation that I've noticed in boosters when we generate a balanced by color pack.  
I just delete the auto include colorless card.
=> Do not always add a colorless card

backend/data.js, frontend/src/lobby/Version.jsx, scripts/download_booster_rules.js
- Fixes #1040
The booster rules version are always redownloaded because we save only the first 7 digits of the hash and check with the entire commit hash
I moved the PR intent (substring 7 first digits of the hash) to frontend. I also added some logs for completeness
=> fix booster rules version

backend/boosterGenerator.js
- Fixes #1080 
We don't add colorless cards in balanced_color sheets. So we don't add lands and colorless cards (artifacts...)
I added the possibility to get also colorless cards in the function that choose a random card
=> fix colorless in colorbalanced sheets

frontend/src/lobby/Version.jsx
Link schema changed with MTGJSON v5 release
=> Fix MTGJSON v4 changelog link

README.md
**Problem**
dr4ft.info was down, decided to stand up my own instance on digital ocean.
After running through setup there and starting the app I was getting 500 errors (not found).
**Solution**
You need to build a production release for there to be a `/built` static folder to serve!
---
Other thoughts:
1. should probably error if this folder doesn't exist
2. could add a `postinstall` script which runs this build...
3. docs need notes on production vs dev setup
4. we could schedule a git pull (of the latest tagged version on github) + npm run build??!
- I checked and the static server doesn't seem to care about mutations in the `built/` folder
- this is a terrible idea ...
=> add "build" to setup steps

.github/workflows/tests.yml
The current tests are run with the names lts and latest but are actually just run twice on version 12, the check-latest tag does nothing.
instead run them on version 12 and 14, travis used 15 which seems unavailable.
=> actually use different versions in tests workflow

backend/game.js
- Fixes #1325
A player joining a game already full was still allowed to enter. 
There's a check at joining that throws an error to the joiner when the game is already full
=> fix game full

frontend/src/cardimage.js, frontend/src/game/Grid.jsx
- Fixes #1346
Basic lands do not have the mtgjson v5 field identifiers.
we add an additional check on identifiers to exist to render the image.
=> add check on identifiers for basic lands

frontend/src/lobby/Version.jsx
- Related https://github.com/dr4fters/dr4ft/pull/1304
Link to MTGJSON changelog did not update with the switch to v5.
Use v5 URL.
=> Fix MTGJSON changelog link

backend/bot.js, backend/human.js, backend/player.js, frontend/src/app.js, frontend/src/events.js, frontend/src/game/card/CardDefault.jsx, frontend/src/game/card/CardGlimpse.jsx, frontend/src/game/card/CardGlimpse.scss, frontend/src/gamestate.js
I've been reading this glimpse logic to see how I can support, and noticed that I was quite confused by the names.
This PR is a trial in aligning the language to be more consistent.
I know that renaming variables can be contentious, so if this does not serve or help, then I'm happy to change this around or close it.
| old language | new language |
|---|---|
| **autopicks** | selected.picks |
| **burns**     | selected.burns |
| isPickReady | isSelectionReady |
| pick      | confirmSelection |
| pickonTimeout | handleTimout |
| pickState (event) | setSelected |
In general:
- cards we're marking are "selected"
- we can select for "pick" (keep) or "burn" (destroy)
- autopick is more a concept about what happens on timeout which is a special case, so we remove the auto prefix most places
=> rename pick + burn vars as types of "selection"

scripts/download_booster_rules.js
in `backends/boosterGenerator.js` there's this section :
```js
const nums = {
"W": cardsByColor["W"].length * numberOfCardsToPick - n,
"B": cardsByColor["B"].length * numberOfCardsToPick - n,
"U": cardsByColor["U"].length * numberOfCardsToPick - n,
"R": cardsByColor["R"].length * numberOfCardsToPick - n,
"G": cardsByColor["G"].length * numberOfCardsToPick - n,
"c": cardsByColor["c"].length * numberOfCardsToPick - n, // <<<< ERROR
};
```
Not all sheets have colorless cards, so you get an Error `can't call length on undefined`.
This results in `makeBoosterFromRules` falling back to `getDefaultBooster` (boooo!)
Was tempted to fix this here but here by having that default to 0, but went upstream
and hit `download_booster_rules.js`
I don't fully know what the implications of this are but it …
=> Errors in boosterGenerator.js 

backend/player/human.js
- Fixes #1391 
Since the work on Glimpse draft and the introduction of "burn" concept, we did not take care of burning cards from decadent draft.
In fact, as we chose to consider the decadent draft as X pick, burn the rest of cards, we forgot to burn them really when the pick selection was confirmed (because the player do not have to burn them manually, it's done by the backend).
Move the burn process at confirmSelection and not at handleTimeout because decadent draft do not select burn cards so we have to calculate them when the selection is confirmed.
=> Fix bug decadent draft not spawning new packs

backend/boosterGenerator.js
- Fixes #1087
We had a problem, for a long time, about representation of colorless card in specific boosters.
=> fix bug of colorless card not showing

backend/data.js, backend/import/keyCards.js
A cube card can now be written as "Abrade (CMR)" or "Abrade (CMR 659)" to specify the exact image that should be displayed. To enable this, the cubable card database has been expanded to include a map from card names to set codes to version numbers, as well as a "default" version for each card that's based on the same logic that's historically been used to select images.
If this approach looks good, I'd like to follow it up with an additional PR that loads card versions from CubeCobra, so that the versions drafted here match the versions specified in the cube list itself.
Here's an image of a cube draft showing off different images for the same card:
=> Add support for specifying particular card versions in a cube

.github/dependabot.yml
- Fixes #1291
It looks like we have to use a conf file for dependabot to work natively with Github
Add a conf file following this guide : 
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/#moving-forward-from-dependabot-com-and-dependabot-preview
=> add dependabot configuration file

backend/data.js
- Fixes #1420
When we create the cards that can be cubable, split cards with name's clashing with other split cards create an issue. 
Fire // ice clashes with Start // Fire and in the end the content of the entry 'fire' depends on which card have been processed last.
We merge the cubable cards with care of clashing: the default value of the card name is calculated based on the priority (expansion > funny, etc). For example, Fire will have its default card being "fire // ice" is the old "fire // ice" and not Start // Fire
=> Rearrange cubable cards with split name clashing

frontend/src/config.js, frontend/src/lobby/Version.jsx, frontend/src/lobby/Version.scss, frontend/src/router.js, frontend/style.css
Been wanting to make these trivial changes for a while!
- Give contribute invitation a little more space with it's own line
- Add some margin between the github logo and the dr4ft repo link (:skull_and_crossbones:)
- reduce the visual focus of the versions bit by moving it to the bottom of the page, away from general lobby use
- give it some styling to make it easier to parse visually
- put some padding around that "Loading..." thing which shows for a second while page is loading
=> little style changes to lobby

frontend/src/events.js
tiny fix - a tidyup from a variable rename in the export refactor/ feature
the problem was it was downloading files as "undefined-draftlog"
=> patch - fix draft log filename

frontend/src/game/PlayersPanel.jsx
- Related to #1442
With the removal of Magic Workstation, the MWS deck hash column got removed.
That way there was a gap in the key numbering.
Use consecutive numbering
=> Cleanup column keys after MWS removal

frontend/src/game/StartPanel.jsx
- Mentioned in https://github.com/dr4fters/dr4ft/issues/1444
The new "pick per pack" value was always displayed.
Display it only for draft games, not sealed.
=> Hide "pick per pack" info for sealed

backend/data.js, frontend/src/game/GameSettings.jsx, frontend/src/utils.spec.js
fixes: https://github.com/dr4fters/dr4ft/issues/1436
Pretty sure I got the bug :bug: 
**desicription** : found that while generating a "random set", that "random set" was one of the options that could be randomly selected... which causes later stuff to explode when it tries to build a booster from a set that is not a set, but a placeholder for a set
**fix** : make sure "random" is excluded from list of set types which can be selected from
NOTE: this fix also means that "custom" and "funny" types will be excluded from random selection (where it looks like they were not in the past, though the code was try to...)
=> bugfix - random sets

frontend/src/export/text.js
The raw text export is not primary intended for machine consumption and not tweaked towards a particular import scheme used by any app - we have the other options for that.
The text export is probably used most by humans and should be as descriptive and informative as possible as it will probably be used to store in draft archives, writing articles or ask some friends for feedback...
- Add deck headline
- Add line break before sideboard starts
All for the looks ✨
=> Prettify text export

package.json
If there is a linting error, 3 CI builds will currently fail.
The `test 12`, `test 14` and our dedicated `eslint` one [which only runs lint](https://github.com/dr4fters/dr4ft/blob/master/.github/workflows/tests.yml#L87). As the test builds might otherwise succeed, one need to manually double check them to be sure what's the issue every time.
I guess we can safely remove it from the tests to improve their expressiveness. Once a PR is created, the linting is still checked super quickly and shown separately... and one can easily run `npm run lint` locally still.
- Remove lint from npm test
=> Remove lint from npm test

frontend/src/export/cockatrice.js, frontend/src/export/cockatrice.spec.js
- Related #1462
When importing decks to Cockatrice via the clipboard, you only see a long single list with no visual breaks.
Now, that there is an empty line between the actual deck and sideboard it's easier navigate in the list and review the import before confirming.
I tested this with some lists and Cockatrice does not care about empty lines.
Fun fact: I realized this way that cards in the `Junk` zone are not exported at all! 🙈 👍
=> Prettify Cockatrice export

backend/data.js
- Fixes #1472
Non-default sets, which are not designed for normal drafting like "Battlebond" used to be part of the random set selection.
Exclude `Draft_Innovation` and `Starter` set types from `Random Set`.
=> More exclusions from random sets

backend/game.js, frontend/src/app.js, frontend/src/game/Grid.jsx, frontend/src/game/Grid.scss, frontend/src/game/card/CardPlaceholder.jsx, frontend/src/game/card/CardPlaceholder.scss
This is a minor tweak which puts placehoder cards in to show the expected number of cards you will receive when the next pack arrives. It stops the UI jumping around so much when a pack arrives and is visually satisfying as the cards "step in" to the shadows that are there already
=> add placeholder cards while waiting for packs

Dockerfile
> (https://github.com/dr4fters/dr4ft/pull/1503#issuecomment-806360781)
>Bad bot. LTS versions of node only
Here you go, @mixmix.
- Use the current active LTS image of Node (same "alpine" base as before)
We have to see if dependabot knows about the LTS tag or still tries to update to 16 once available. Then, we can still exclude the Dockerfile from dependabot updates.
=> Dockerfile: Use Node LTS-alpine

frontend/src/game/card/CardBase.jsx
If a card doesn't have an image at all (for example, because it's a
custom hard without an image link) this prevents an unsightly broken
`img` tag from appearing.
=> Don't show a broken image for cards without images

backend/data.spec.js
One of the unit tests was assuming a forward slash seperator,
even though the implementation uses path.join(). This meant the
test would fail on Windows platforms because on Windows path.join()
would use a back slash path seperator.
Type: Bug Fix
=> Fix can get data directory test for Windows

frontend/src/components/Modal.jsx, frontend/src/components/Modal.scss, frontend/src/components/Switch.jsx, frontend/src/components/Switch.scss, frontend/src/game/Cols.scss, frontend/src/game/Grid.jsx, frontend/src/game/Grid.scss, frontend/src/game/PlayersPanel.jsx, frontend/src/game/PlayersPanel.scss, frontend/src/game/card/CardBase.scss, frontend/src/game/card/CardDefault.scss, frontend/src/game/card/CardGlimpse.scss, frontend/src/lobby/CreateGameButton.jsx, frontend/src/lobby/CreateGameButton.scss, frontend/src/lobby/GamesPanel.jsx, frontend/src/lobby/GamesPanel.scss, frontend/src/lobby/Lobby.jsx, frontend/src/lobby/SelectSet.scss, frontend/style.css
The UI was a bit cluttered when using it in mobile. This is a first pass fixing that.
Changed the CSS of:
- **main drafting area** shrink to fit two columns of cards, drops page padding down
- **main game creating modal** so it fits on mobile
Component changes:
- on the home page, merged "create room + join room => Games"
- pulling the sections together makes it very clear that making a game could put it in the list of games to join
-  renaming rooms > games because ... what is a room but a game that's yet to start? Feels like a good simplification to me
- in the create game model, changed the public/ private selector to a **toggle** 
I'm keen to revisit some of the designs someone did and make this app really a delight to look at and use. 
landing page | create game | draft 
---|---|---
=> Mobile friendly

frontend/src/lobby/Version.jsx
Footer included some not really necessary text.
That resulted in forced line breaks with the more narrow layout and on smaller screens.
Only keep relevant hints and links.
Displays all version information in one line again (at least on desktop)
=> Simpler footer

backend/import/xml/parser.js
having a pt of something that is not a string in your custom xml will result in an error:
min example:
```xml
<?xml version="1.0" encoding="UTF-8"?>                                          
<cockatrice_carddatabase version="4">
<sets>
<set>
<name>X</name>
</set>
</sets>
<cards>
<card>
<name>TEST CARD PLEASE IGNORE 6</name>
<set rarity="common">X</set>
<prop>
<pt>8</pt>
</prop>
</card>
</cards>
</cockatrice_carddatabase>
```
casts pt to a string before using .split
=> make pt a string for sure

frontend/src/lobby/Lobby.jsx
Fixes https://github.com/dr4fters/dr4ft/issues/1533.
Hides the News panel if there is no 'message of the day' (a.k.a. 'motd') to display to users.
=> ISSUE-1533: Hide news panel if no message of the day

backend/hash.js
cockatrice hashes are always 8 characters and padded with zeros: https://github.com/Cockatrice/Cockatrice/blob/1c48656623e03e065d21d27a8bdfe1cfcdcaa71c/common/decklist.cpp#L830
=> add padding to cockatrice hash

frontend/src/lobby/CubeList.jsx
CubeCobra's JSON response (since 5.9?) was changed; the 'cards' object used to hold an array of cards, now it has sub-objects 'mainboard' and 'maybeboard' with the card arrays.
- Fixes #1709
=> update cube import for CubeCobra API change

frontend/src/lobby/FileUpload.jsx
- Issue: #1432
- Temporary workaround from over a year ago: #1453
The root cause of the initial issue will very likely not be resolved anytime soon.
Instead showing a hint in the interface and tell the users that we are working on it (which nobody is), transfer it into a `TODO` note.
We also have the above linked issue tracking the problem in our repo: https://github.com/dr4fters/dr4ft/issues/1432
The UI clearly states what is supported already, no reason to highlight that there used to be something else which is not working anymore (= support for JSON uploads).
=> Cleanup old upload hint
